bash scripts/train_lora_hf_CONCODE.sh
bash scripts/train_lora_hf_CodeTrans.sh
bash scripts/train_lora_hf_CodeSearchNet.sh
bash scripts/train_lora_hf_BFP.sh
bash scripts/train_lora_hf_TheVault_Csharp.sh
bash scripts/train_lora_hf_KodCode.sh
bash scripts/train_lora_hf_RunBugRun.sh
bash scripts/train_lora_hf_CoST.sh